"""empty message

Revision ID: 6ed1a15d9a73
Revises: 
Create Date: 2023-12-29 10:52:12.563656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed1a15d9a73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revoked_token', sa.String(length=120), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_token_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_token_id'))

    op.drop_table('revoked_token')
    # ### end Alembic commands ###
